### PR TITLE
fix(git): fix resolution of prerelease versions

### LINKED ISSUE #129: Git semver does not resolve versions with prerelease or build info
To reproduce:
Add git dependency with semver pointing to regular version e.g. v1.0.0
-> it works as expected
Change git dependency to prerelease version e.g. v1.0.1-0
-> no matching version is found (even if tag exists)

### PR DESCRIPTION
**Pull request by spraot**
Closes #129 

This will match any tags that match with earlier versions AND any tags ending with a valid semver. This maintains the (intentional?) behavior of ignoring any text preceding the valid semver.

This should allow for fully functional git semver dependencies.

### CODE REVIEW

**Comment by spraot** [comment]
The travis-ci tests seem to be failing for zkat:latest (see [here](https://travis-ci.org/rachetfoot/pacote/jobs/324505514)) and not due to the changes in my pull request. Tests fail locally for me as well, but in a different way, so I hope that someone with a known good setup will have a look it.

File: lib/util/git.js [hunk 1]
```diff
@@ -141,8 +142,8 @@ function revs (repo, opts) {
           }
 
           if (type === 'tag') {
-            const match = ref.match(/v?(\d+\.\d+\.\d+)$/)
-            if (match) {
+            const match = ref.match(/v?(\d+\.\d+\.\d+(?:[-+].+)?)$/)
+            if (match && semver.valid(match[1])) {
```
Comment (zkat) [inline lib/util/git.js]: This needs to make sure it's using loose mode, so two changes:

1. `semver.valid()` needs to get `true` as its second arg, so it'll do validity checks in loose mode.
2. `semver.clean()` should be called on `match[1]` to clean up the spec. It also needs the second `true` arg for loose mode.

**Review by zkat — CHANGES_REQUESTED** [review]
Thanks for this! This mostly lgtm, and I really appreciate help with the git stuff.

There's a couple of minor changes I'd like to see, but besides that, this LGTM!

File: lib/util/git.js (hunk 1 above)
Comment (spraot) [reply lib/util/git.js]: Great, this will fix a big pain point for me in NPM. I just pushed a commit re your comments.

**Comment by spraot** [comment]
@zkat Are things alright now?

**Review by zkat — APPROVED** [review]
LGTM! Thank you!
